# Generated by Django 5.2.6 on 2025-09-21 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('staff', 'Staff')], max_length=7)),
                ('full_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='CitizenDetails',
            fields=[
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.users')),
                ('reward_points', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'citizen_details',
            },
        ),
        migrations.CreateModel(
            name='FieldStaffDetails',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.users')),
                ('shift_start_time', models.TimeField(blank=True, null=True)),
                ('shift_end_time', models.TimeField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=8)),
            ],
            options={
                'db_table': 'field_staff_details',
            },
        ),
        migrations.CreateModel(
            name='PickupSchedules',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('next_pickup_date', models.DateField(blank=True, null=True)),
                ('next_pickup_time', models.TimeField(blank=True, null=True)),
                ('waste_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Scheduled', max_length=9)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
            options={
                'db_table': 'pickup_schedules',
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=100)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.users')),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=11)),
                ('qr_code_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.routes')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='CollectionLogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_time', models.DateTimeField(auto_now_add=True)),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.users')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tasks')),
            ],
            options={
                'db_table': 'collection_logs',
            },
        ),
    ]
